_target_: icenet_mp.models.EncodeProcessDecode

name: naive-unet-naive

encoder:
  _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  latent_space: [128, 128] # Shape of the latent space

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  kernel_size: 3 # Size of the kernel for convolutional layers
  start_out_channels: 64 # Initial number of channels for the first convolutional layer

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
