_target_: icenetmp.models.EncodeProcessDecode

name: cnn-null-cnn

encoder:
  _target_: icenetmp.models.encoders.CNNEncoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  latent_space: [128, 128] # Shape of the latent space
  n_layers: 3 # Number of convolutional layers

processor:
  _target_: icenetmp.models.processors.NullProcessor

decoder:
  _target_: icenetmp.models.decoders.CNNDecoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  n_layers: 3 # Number of convolutional layers
  bounded: false # Whether to bound the output between 0 and 1
