_target_: icenetmp.models.EncodeProcessDecode

name: naive-vit-naive

encoder:
  _target_: icenetmp.models.encoders.NaiveLinearEncoder
  latent_space: [192, 192] # Shape of the latent space

processor:
  _target_: icenetmp.models.processors.VitProcessor
  patch_size: 16
  emb_dim: 128
  depth: 3
  heads: 4
  mlp_dim: 256
  dropout: 0.3

decoder:
  _target_: icenetmp.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
