_target_: ice_station_zebra.models.EncodeProcessDecode
mod_antialias: ${..antialias_val}

name: naive-ddpm-naive

encoder:
  _target_: ice_station_zebra.models.encoders.NaiveLinearEncoder
  latent_space: [128, 128] # Shape of the latent space
  antialias: ${..mod_antialias}

processor:
  _target_: ice_station_zebra.models.processors.DDPMProcessor
  timesteps: 1000 # DDPM timesteps

decoder:
  _target_: ice_station_zebra.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
  antialias: ${..mod_antialias}
