_target_: ice_station_zebra.models.EncodeProcessDecode
mod_antialias: ${..antialias_val}

name: naive-unet-naive

encoder:
  _target_: ice_station_zebra.models.encoders.NaiveLinearEncoder
  latent_space: [128, 128] # Shape of the latent space
  antialias: ${..mod_antialias}

processor:
  _target_: ice_station_zebra.models.processors.UNetProcessor
  kernel_size: 3 # Size of the kernel for convolutional layers
  start_out_channels: 64 # Initial number of channels for the first convolutional layer

decoder:
  _target_: ice_station_zebra.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
  antialias: ${..mod_antialias}
