# Base config inherited by all other configs
defaults:
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: osisaf-south
  - train: default
  - _self_

antialias_val: true # Global setting for antialiasing in encoders/decoders - fixing Mac bug
