# Base config inherited by all other configs
defaults:
  - data: sample
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: sic-osisaf
  - train: default
  - _self_

antialias_val: true # Global setting for antialiasing in encoders/decoders - fixing Mac bug
base_path: ../zebra
