defaults:
  - base
  - _self_

train:
  trainer:
    max_epochs: 10

loggers:
  wandb:
    name: naive_unet_naive_demo_south
    entity: null
    save_dir: ${...base_path}/training/${loggers.wandb.name}/

base_path: ../my_data
antialias_val: false 