defaults:
  - datasets:
    - full_sicnorth_osisaf_25k_1979_2024_24h_v1
    - full_sicsouth_osisaf_25k_1979_2024_24h_v1
    - full_weathernorth_era5_0p5_1979_2024_24h_v1
    - full_weathersouth_era5_0p5_1979_2024_24h_v1
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: osisaf-south
  - split: full_dataset
  - train: default
  - _self_

base_path: /bask/projects/v/vjgo8416-ice-frcst/shared/zebra/
antialias_val: true # Global setting for antialiasing in encoders/decoders - fixing Mac bug
